name: shsh_social
description: "SHSH Messanger"
publish_to: 'none'
version: 0.4.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Audio & Video
  camera: 0.11.1
  mobile_scanner: 6.0.6

  # UI & Animation
  flutter_staggered_grid_view: 0.7.0
  fl_chart: 0.70.2
  lottie: 3.3.1
  confetti: 0.8.0
  photo_view: 0.15.0
  flutter_swiper_null_safety: 1.0.2
  line_icons: 2.0.3

  # Firebase
  firebase_core: 3.11.0
  firebase_messaging: 15.2.2

  #HSM
  # huawei_push: ^6.12.0+303

  # State Management
  flutter_bloc: 8.1.6
  equatable: 2.0.7

  # Network & Caching
  cached_network_image: 3.4.1
  http: 1.3.0
  stomp_dart_client: 2.1.3
  dio: ^5.8.0+1

  # Storage
  shared_preferences: 2.5.1
  sqflite: 2.4.1

  # File & Media Handling
  image_picker: 1.1.2
  open_file: 3.5.10
  flutter_downloader: 1.12.0

  # Notifications
  flutter_local_notifications: 18.0.1
  flutter_timezone: 4.1.0
  windows_notification: ^1.3.0

  # Utilities
  intl: 0.19.0
  device_info_plus: 10.1.2
  clipboard: 0.1.3
  connectivity_plus: 6.1.3
  permission_handler: 11.3.1
  url_launcher: 6.3.1
  dartz: ^0.10.1
  google_api_availability: ^5.0.1

  # Specialized Widgets
  pro_image_editor: 8.3.1
  signature: 5.5.0
  qr_flutter: 4.1.0

  # Web & Platform Specific
  universal_io: 2.2.2
  pasteboard: ^0.3.0
  sqflite_common_ffi: ^2.3.5
  pedometer: ^4.0.2
  flame: ^1.25.0
  html: ^0.15.5
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0
  flutter_rustore_billing: ^8.0.0

analyzer:
  errors:
    unused_import: error  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.14
  freezed: 2.5.8
  json_serializable: 6.9.3
  flutter_launcher_icons: 0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/mini_apps/images/
    - assets/audio/
    - assets/categories/
  fonts:
    - family: Sketch
      fonts:
        - asset: assets/fonts/Sketch.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

  flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/icon.png"
    min_sdk_android: 21 